name: wookie_movies_flutter_yisxmq
description: "Thikkiiana City ultimate movie theater app!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter_bloc: ^9.1.0
  http: ^1.3.0
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  injectable: ^2.1.2
  get: ^4.7.2
  get_it: ^8.0.3
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.4
  bloc_test: ^10.0.0
  mockito: ^5.4.5
  test: ^1.24.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
